### ISSUE TITLE
Talk Request: Lightning Talks on Ticket Deployment Status/Process

### ISSUE THREAD

**Issue by erindethorne** [websdev/lunch#21]
### Questions I don't know the answer to:
- What is the process around code deployments? Who manages them? 
- How can I find out if a ticket is deployed and to what environment?
- Is there any kind of notification system in place? Is there a dashboard that reports this? Is it a team member's responsibility to update JIRA status?

I'm guessing that the answers to the above questions are different depending on codebases, products, and teams. I'm also guessing I'm not alone in my lack of knowledge about how things work across the board.

### Proposal:
- A lightning-talk style session with multiple presenters, each knowledgable about some codebase's deployment process and status reporting.
- We'll need representatives to talk about each of the following:
  - [ ] Webs
  - [ ] Tower
  - [ ] Vistaprint Monolith
  - [ ] Vistaprint Off-monolith services
  - [x] Pagemodo - @erindethorne
  - What am I missing?

I can volunteer to talk about Pagemodo. If you're also interested in this topic and are knowledgable about one of the above areas, please sign up to join me in this talk! If you can think of something I'm forgetting that ought to be in this list, please add it! And finally, if you're just plain interested but are not prepared to talk, just give me a :+1: to promote the idea :smile:

**Comment by nchase** [comment]
:thumbsup:

**Comment by ayobami14** [comment]
:+1:

**Comment by HackAttack** [comment]
Bamboo gives you this information in the Development panel in JIRA:

![screen shot 2015-06-30 at 11 13 57 am](https://cloud.githubusercontent.com/assets/1222646/8434415/2e913776-1f19-11e5-8b54-6e04bfc02637.png)

This cuts down on manual bookkeeping.

**Comment by nmielnik** [comment]
:+1:

**Comment by erindethorne** [comment]
@HackAttack if only we had bamboo everywhere :smiley:

**Comment by HackAttack** [comment]
:smiling_imp: :tada:

**Comment by twisterghost** [comment]
:bamboo:
